#ifndef COMMONSTRUCT_H
#define COMMONSTRUCT_H

#include "CoreMacro.h"
#include "CoreHeader.h"

struct IdentifyDeviceData {
    struct {
        U16 Reserved1  :1;
        U16 Retired3  :1;
        U16 ResponseIncomplete  :1;
        U16 Retired2  :3;
        U16 FixedDevice  :1;
        U16 RemovableMedia  :1;
        U16 Retired1  :7;
        U16 DeviceType  :1;
    } GeneralConfiguration;
    U16 NumCylinders;
    U16 ReservedWord2;
    U16 NumHeads;
    U16 Retired1[2];
    U16 NumSectorsPerTrack;
    U16 VendorUnique1[3];
    U8  SerialNumber[20];
    U16 Retired2[2];
    U16 Obsolete1;
    U8  FirmwareRevision[8];
    U8  ModelNumber[40];
    U8  MaximumBlockTransfer;
    U8  VendorUnique2;
    U16 ReservedWord48;
    struct {
        U8  ReservedByte49;
        U8  DmaSupported  :1;
        U8  LbaSupported  :1;
        U8  IordyDisable  :1;
        U8  IordySupported  :1;
        U8  Reserved1  :1;
        U8  StandybyTimerSupport  :1;
        U8  Reserved2  :2;
        U16 ReservedWord50;
    } Capabilities;
    U16 ObsoleteWords51[2];
    U16 TranslationFieldsValid  :3;
    U16 Reserved3  :13;
    U16 NumberOfCurrentCylinders;
    U16 NumberOfCurrentHeads;
    U16 CurrentSectorsPerTrack;
    U32  CurrentSectorCapacity;
    U8  CurrentMultiSectorSetting;
    U8  MultiSectorSettingValid  :1;
    U8  ReservedByte59  :7;
    U32  UserAddressableSectors;
    U16 ObsoleteWord62;
    U16 MultiWordDMASupport  :8;
    U16 MultiWordDMAActive  :8;
    U16 AdvancedPIOModes  :8;
    U16 ReservedByte64  :8;
    U16 MinimumMWXferCycleTime;
    U16 RecommendedMWXferCycleTime;
    U16 MinimumPIOCycleTime;
    U16 MinimumPIOCycleTimeIORDY;
    U16 ReservedWords69[6];
    U16 QueueDepth  :5;
    U16 ReservedWord75  :11;
    U16 ReservedWords76[4];
    U16 MajorRevision;
    U16 MinorRevision;
    struct {
        U16 SmartCommands  :1;
        U16 SecurityMode  :1;
        U16 RemovableMediaFeature  :1;
        U16 PowerManagement  :1;
        U16 Reserved1  :1;
        U16 WriteCache  :1;
        U16 LookAhead  :1;
        U16 ReleaseInterrupt  :1;
        U16 ServiceInterrupt  :1;
        U16 DeviceReset  :1;
        U16 HostProtectedArea  :1;
        U16 Obsolete1  :1;
        U16 WriteBuffer  :1;
        U16 ReadBuffer  :1;
        U16 Nop  :1;
        U16 Obsolete2  :1;
        U16 DownloadMicrocode  :1;
        U16 DmaQueued  :1;
        U16 Cfa  :1;
        U16 AdvancedPm  :1;
        U16 Msn  :1;
        U16 PowerUpInStandby  :1;
        U16 ManualPowerUp  :1;
        U16 Reserved2  :1;
        U16 SetMax  :1;
        U16 Acoustics  :1;
        U16 BigLba  :1;
        U16 DeviceConfigOverlay  :1;
        U16 FlushCache  :1;
        U16 FlushCacheExt  :1;
        U16 Resrved3  :2;
        U16 SmartErrorLog  :1;
        U16 SmartSelfTest  :1;
        U16 MediaSerialNumber  :1;
        U16 MediaCardPassThrough  :1;
        U16 StreamingFeature  :1;
        U16 GpLogging  :1;
        U16 WriteFua  :1;
        U16 WriteQueuedFua  :1;
        U16 WWN64Bit  :1;
        U16 URGReadStream  :1;
        U16 URGWriteStream  :1;
        U16 ReservedForTechReport  :2;
        U16 IdleWithUnloadFeature  :1;
        U16 Reserved4  :2;
    } CommandSetSupport;
    struct {
        U16 SmartCommands  :1;
        U16 SecurityMode  :1;
        U16 RemovableMediaFeature  :1;
        U16 PowerManagement  :1;
        U16 Reserved1  :1;
        U16 WriteCache  :1;
        U16 LookAhead  :1;
        U16 ReleaseInterrupt  :1;
        U16 ServiceInterrupt  :1;
        U16 DeviceReset  :1;
        U16 HostProtectedArea  :1;
        U16 Obsolete1  :1;
        U16 WriteBuffer  :1;
        U16 ReadBuffer  :1;
        U16 Nop  :1;
        U16 Obsolete2  :1;
        U16 DownloadMicrocode  :1;
        U16 DmaQueued  :1;
        U16 Cfa  :1;
        U16 AdvancedPm  :1;
        U16 Msn  :1;
        U16 PowerUpInStandby  :1;
        U16 ManualPowerUp  :1;
        U16 Reserved2  :1;
        U16 SetMax  :1;
        U16 Acoustics  :1;
        U16 BigLba  :1;
        U16 DeviceConfigOverlay  :1;
        U16 FlushCache  :1;
        U16 FlushCacheExt  :1;
        U16 Resrved3  :2;
        U16 SmartErrorLog  :1;
        U16 SmartSelfTest  :1;
        U16 MediaSerialNumber  :1;
        U16 MediaCardPassThrough  :1;
        U16 StreamingFeature  :1;
        U16 GpLogging  :1;
        U16 WriteFua  :1;
        U16 WriteQueuedFua  :1;
        U16 WWN64Bit  :1;
        U16 URGReadStream  :1;
        U16 URGWriteStream  :1;
        U16 ReservedForTechReport  :2;
        U16 IdleWithUnloadFeature  :1;
        U16 Reserved4  :2;
    } CommandSetActive;
    U16 UltraDMASupport  :8;
    U16 UltraDMAActive  :8;
    U16 ReservedWord89[4];
    U16 HardwareResetResult;
    U16 CurrentAcousticValue  :8;
    U16 RecommendedAcousticValue  :8;
    U16 ReservedWord95[5];
    U32  Max48BitLBA[2];
    U16 StreamingTransferTime;
    U16 ReservedWord105;
    struct {
        U16 LogicalSectorsPerPhysicalSector  :4;
        U16 Reserved0  :8;
        U16 LogicalSectorLongerThan256Words  :1;
        U16 MultipleLogicalSectorsPerPhysicalSector  :1;
        U16 Reserved1  :2;
    } PhysicalLogicalSectorSize;
    U16 InterSeekDelay;
    U16 WorldWideName[4];
    U16 ReservedForWorldWideName128[4];
    U16 ReservedForTlcTechnicalReport;
    U16 WordsPerLogicalSector[2];
    struct {
        U16 ReservedForDrqTechnicalReport  :1;
        U16 WriteReadVerifySupported  :1;
        U16 Reserved01  :11;
        U16 Reserved1  :2;
    } CommandSetSupportExt;
    struct {
        U16 ReservedForDrqTechnicalReport  :1;
        U16 WriteReadVerifyEnabled  :1;
        U16 Reserved01  :11;
        U16 Reserved1  :2;
    } CommandSetActiveExt;
    U16 ReservedForExpandedSupportandActive[6];
    U16 MsnSupport  :2;
    U16 ReservedWord1274  :14;
    struct {
        U16 SecuritySupported  :1;
        U16 SecurityEnabled  :1;
        U16 SecurityLocked  :1;
        U16 SecurityFrozen  :1;
        U16 SecurityCountExpired  :1;
        U16 EnhancedSecurityEraseSupported  :1;
        U16 Reserved0  :2;
        U16 SecurityLevel  :1;
        U16 Reserved1  :7;
    } SecurityStatus;
    U16 ReservedWord129[31];
    struct {
        U16 MaximumCurrentInMA2  :12;
        U16 CfaPowerMode1Disabled  :1;
        U16 CfaPowerMode1Required  :1;
        U16 Reserved0  :1;
        U16 Word160Supported  :1;
    } CfaPowerModel;
    U16 ReservedForCfaWord161[8];
    struct {
        U16 SupportsTrim  :1;
        U16 Reserved0  :15;
    } DataSetManagementFeature;
    U16 ReservedForCfaWord170[6];
    U16 CurrentMediaSerialNumber[30];
    U16 ReservedWord206;
    U16 ReservedWord207[2];
    struct {
        U16 AlignmentOfLogicalWithinPhysical  :14;
        U16 Word209Supported  :1;
        U16 Reserved0  :1;
    } BlockAlignment;
    U16 WriteReadVerifySectorCountMode3Only[2];
    U16 WriteReadVerifySectorCountMode2Only[2];
    struct {
        U16 NVCachePowerModeEnabled  :1;
        U16 Reserved0  :3;
        U16 NVCacheFeatureSetEnabled  :1;
        U16 Reserved1  :3;
        U16 NVCachePowerModeVersion  :4;
        U16 NVCacheFeatureSetVersion  :4;
    } NVCacheCapabilities;
    U16 NVCacheSizeLSW;
    U16 NVCacheSizeMSW;
    U16 NominalMediaRotationRate;
    U16 ReservedWord218;
    struct {
        U8 NVCacheEstimatedTimeToSpinUpInSeconds;
        U8 Reserved;
    } NVCacheOptions;
    U16 ReservedWord220[35];
    U16 Signature  :8;
    U16 CheckSum  :8;
};

struct InquiryData {
    U8 DeviceType  :5;
    U8 DeviceTypeQualifier  :3;
    U8 DeviceTypeModifier  :7;
    U8 RemovableMedia  :1;
    union {
        U8  Versions;
        struct {
            U8 ANSIVersion  :3;
            U8 ECMAVersion  :3;
            U8 ISOVersion  :2;
        };
    };
    U8 ResponseDataFormat  :4;
    U8 HiSupport  :1;
    U8 NormACA  :1;
    U8 TerminateTask  :1;
    U8 AERC  :1;
    U8 AdditionalLength;
    U8 Reserved;
    U8 Addr16  :1;
    U8 Addr32  :1;
    U8 AckReqQ  :1;
    U8 MediumChanger  :1;
    U8 MultiPort  :1;
    U8 ReservedBit2  :1;
    U8 EnclosureServices  :1;
    U8 ReservedBit3  :1;
    U8 SoftReset  :1;
    U8 CommandQueue  :1;
    U8 TransferDisable  :1;
    U8 LinkedCommands  :1;
    U8 Synchronous  :1;
    U8 Wide16Bit  :1;
    U8 Wide32Bit  :1;
    U8 RelativeAddressing  :1;
    U8 VendorId[8];
    U8 ProductId[16];
    U8 ProductRevisionLevel[4];
    U8 VendorSpecific[20];
    U8 Reserved3[40];
};

string GetInquiryDataString(const U8* buffer);
string GetIdentifyDataString(const U8* buffer);

#endif // COMMONSTRUCT_H
